version: '3'

services:
  master:
    image: ${ACCT_NO}.dkr.ecr.${REGION}.amazonaws.com/s3locust:latest
    ports:
     - "8089:8089"
    command: --master -H http://master:8089
  
  worker:
    image: ${ACCT_NO}.dkr.ecr.${REGION}.amazonaws.com/s3locust:latest
    command: --worker --master-host master
