version: '3'

services:
  swarm-leader:
    image: ${ACCT_NO}.dkr.ecr.${REGION}.amazonaws.com/s3locust:latest
    ports:
      - "8089:8089"
    command: "--master -H http://swarm-leader:8089"

  worker:
    image: ${ACCT_NO}.dkr.ecr.${REGION}.amazonaws.com/s3locust:latest
    command: "--worker --master-host swarm-leader"
    deploy:
      replicas: 5
