version: '3'

services:
  master:
    image: jpbarto/locust
    ports:
     - "8089:8089"
    command: --master -H http://master:8089
  
  worker:
    image: jpbarto/locust
    command: --worker --master-host master
